FROM node:22-alpine
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
# Set the port environment variable for Next.js
ENV PORT=8080
RUN npm run build
EXPOSE 8080
CMD ["npm", "start"]