env:
  NODE_ENV: staging
    # AWS region for IRSA (no credentials needed)
  AWS_REGION: us-east-1
  NEXT_PUBLIC_API_URL: https://document-intelligence.industrysolutions.staging.corp.mongodb.com
  
# Secret environment variables (references to K8s secrets)
envSecrets:
  NEXT_PUBLIC_API_URL: document-intelligence-ui-secrets

# Add IRSA configuration here
serviceAccount:
  enabled: true
  # create: false  # Don't create a new service account
  name: irsa-staging  # Use the existing one
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::275662791714:role/kanopy-staging-cicd-irsa