env:
  NODE_ENV: staging
  # Internal K8s service URL for backend communication (server-side only)
  INTERNAL_API_URL: http://document-intelligence-web-app:80
  
envSecrets:
  NEXT_PUBLIC_API_URL: document-intelligence-ui
  NODE_ENV: document-intelligence-ui

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-staging-cicd-irsa"