env:
  NODE_ENV: staging
  
envSecrets:
  NEXT_PUBLIC_API_URL: document-intelligence-ui
  NODE_ENV: document-intelligence-ui

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-staging-cicd-irsa"