env:
  NODE_ENV: staging
  # Use internal k8s service - bypasses authentication
  NEXT_PUBLIC_INTERNAL_API_URL: http://document-intelligence-web-app:80
  # Keep external URL as fallback (though it won't be used due to auth issues)
  NEXT_PUBLIC_API_URL: http://document-intelligence-web-app:80

# No service account needed for frontend
serviceAccount:
  enabled: false